src/Entity/Aulas.php
<?php

namespace App\Entity;

use App\Repository\AulasRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AulasRepository::class)
 */
class Aulas
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $aula;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $capacidad;

    /**
     * @ORM\OneToMany(targetEntity=Ocupacion::class, mappedBy="id_aula")
     */
    private $ocupacions;

    /**
     * @ORM\ManyToOne(targetEntity=Edificios::class, inversedBy="aulas")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_edificio;

    /**
     * @ORM\ManyToOne(targetEntity=EdificiosPisos::class, inversedBy="aulas")
     */
    private $id_piso;

    public function __construct()
    {
        $this->ocupacions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAula(): ?string
    {
        return $this->aula;
    }

    public function setAula(string $aula): self
    {
        $this->aula = $aula;

        return $this;
    }

    public function getCapacidad(): ?int
    {
        return $this->capacidad;
    }

    public function setCapacidad(?int $capacidad): self
    {
        $this->capacidad = $capacidad;

        return $this;
    }

    /**
     * @return Collection|Ocupacion[]
     */
    public function getOcupacions(): Collection
    {
        return $this->ocupacions;
    }

    public function addOcupacion(Ocupacion $ocupacion): self
    {
        if (!$this->ocupacions->contains($ocupacion)) {
            $this->ocupacions[] = $ocupacion;
            $ocupacion->setIdAula($this);
        }

        return $this;
    }

    public function removeOcupacion(Ocupacion $ocupacion): self
    {
        if ($this->ocupacions->removeElement($ocupacion)) {
            // set the owning side to null (unless already changed)
            if ($ocupacion->getIdAula() === $this) {
                $ocupacion->setIdAula(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->aula;
    }

    public function getIdEdificio(): ?Edificios
    {
        return $this->id_edificio;
    }

    public function setIdEdificio(?Edificios $id_edificio): self
    {
        $this->id_edificio = $id_edificio;

        return $this;
    }

    public function getIdPiso(): ?EdificiosPisos
    {
        return $this->id_piso;
    }

    public function setIdPiso(?EdificiosPisos $id_piso): self
    {
        $this->id_piso = $id_piso;

        return $this;
    }
}

src/Form/AulasType.php
<?php

namespace App\Form;

use App\Entity\Aulas;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AulasType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('aula')
            ->add('capacidad')
            ->add('id_edificio')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Aulas::class,
        ]);
    }
}

src/Controller/AulasController.php
<?php

namespace App\Controller;

use App\Entity\Aulas;
use App\Form\AulasType;
use App\Repository\AulasRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Session\SessionInterface;

/**
 * @Route("/aulas")
 */
class AulasController extends AbstractController
{
    public function __construct(private ManagerRegistry $doctrine) {}

    /**
     * @Route("/", name="aulas_index", methods={"GET"})
     * 
     * @IsGranted("ROLE_USER")
     */
    public function index(Request $request, AulasRepository $aulasRepository, SessionInterface $session): Response
    {
        $edificio = $request->query->get('edificio', 0);
        if ($edificio==0) {
            $edificio = $session->get('id_edificio');
        }

        return $this->render('aulas/index.html.twig', [
            'aulas' => $aulasRepository->findBy(['id_edificio'=>$edificio], ['id_edificio'=>'ASC', 'id_piso'=>'ASC']),
        ]);
    }

    /**
     * @Route("/new", name="aulas_new", methods={"GET","POST"})
     * 
     * @IsGranted("ROLE_ADMIN")
     */
    public function new(Request $request): Response
    {
        $aula = new Aulas();
        $form = $this->createForm(AulasType::class, $aula);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->doctrine->getManager();
            $entityManager->persist($aula);
            $entityManager->flush();

            return $this->redirectToRoute('aulas_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('aulas/new.html.twig', [
            'aula' => $aula,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="aulas_show", methods={"GET"})
     * 
     * @IsGranted("ROLE_USER")
     */
    public function show(Aulas $aula): Response
    {
        return $this->render('aulas/show.html.twig', [
            'aula' => $aula,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="aulas_edit", methods={"GET","POST"})
     * 
     * @IsGranted("ROLE_ADMIN")
     */
    public function edit(Request $request, Aulas $aula): Response
    {
        $form = $this->createForm(AulasType::class, $aula);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->doctrine->getManager()->flush();

            return $this->redirectToRoute('aulas_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('aulas/edit.html.twig', [
            'aula' => $aula,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="aulas_delete", methods={"POST"})
     * 
     * @IsGranted("ROLE_ADMIN")
     */
    public function delete(Request $request, Aulas $aula): Response
    {
        if ($this->isCsrfTokenValid('delete'.$aula->getId(), $request->request->get('_token'))) {
            $entityManager = $this->doctrine->getManager();
            $entityManager->remove($aula);
            $entityManager->flush();
        }

        return $this->redirectToRoute('aulas_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/aulas/_delete_form.html.twig
<form method="post" action="{{ path('aulas_delete', {'id': aula.id}) }}" onsubmit="return confirm('¿Borrar Aula?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ aula.id) }}">
    <button class="btn btn-danger">Borrar</button>
</form>

templates/aulas/_form.html.twig
<div class="container">
	<div class="card text-center">
		<div class="card-body">
			{{ form_start(form) }}
			<div class="input-group mb-3">
				<div class="input-group mb-3">
					<div class="col-8">
						<span class="input-group-text">Edificio</span>
						{{ form_widget(form.id_edificio) }}</div>
					<div class="col-4">
						<span class="input-group-text">Piso</span>
						{{ form_widget(form.id_piso) }}</div>
				</div>
				<div class="input-group mb-3">
					<div class="col-6">
						<span class="input-group-text">Aula</span>
						{{ form_widget(form.aula) }}</div>
					<div class="col-2">
						<span class="input-group-text">Capacidad</span>
						{{ form_widget(form.capacidad) }}</div>
				</div>
				<button type="submit" class="btn btn-primary">Guardar</button>
			</div>
			{{ form_end(form) }}
		</div>
	</div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
	// filtrar Pisos por Edificio
var selEdificio = $('#aulas_id_edificio');
var selPiso = $('#aulas_id_piso');
$('#aulas_id_edificio').change(function () {
selPiso.html('');
if (selEdificio.val() > 0) {
$.ajax({
url: '/edificios/' + selEdificio.val() + '/pisos',
type: 'POST',
dataType: 'JSON'
}).done(function (pisos) {
$.each(pisos, function (key, piso) {
selPiso.append('<option value="' + piso.id + '">' + piso.piso + '</option>');
});
});
}
});
</script>

templates/aulas/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editar Aula{% endblock %}
{% block cardheader %}
	<div class="col-sm-11">
		<h5>Editar Aula</h5>
	</div>
	<div class="col-sm-1">
         {{ include('aulas/_delete_form.html.twig') }}
	</div>
{% endblock %}

{% block cardbody %}
    {{ include('aulas/_form.html.twig', {'button_label': 'Update'}) }}
    <a href="{{ path('aulas_index') }}" class="btn btn-sm btn-outline-secondary" role="button">volver</a>
{% endblock %}

templates/aulas/index.html.twig
{% extends 'base.html.twig' %}

{% block cardheader %}
	<div class="col-sm-8">
		<h5><i class="bi bi-columns"></i> {{aulas[0].IdEdificio.edificio}} <i class="bi bi-arrow-right-short"></i> Aulas</h5>
	</div>
    <div class="col-sm-4">
        <a href="{{ path('aulas_new') }}" class="btn btn-sm btn-outline-secondary" role="button"><i class="bi bi-plus-square"></i> Nueva</a>
    </div>
{% endblock %}
{% block cardbody %}
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Aula</th>
                <th>Capacidad</th>
                <th>Edificio</th>
                <th>Piso</th>
                {# <th>acciones</th> #}
            </tr>
        </thead>
        <tbody>
        {% for aula in aulas %}
            <tr>
                <td>{{ aula.id }}</td>
                <td>{{ aula.aula }}</td>             
                <td>{{ aula.capacidad }}</td>
                <td>{{ aula.IdEdificio.edificio }}</td>
                <td>{{ aula.IdPiso.piso }}</td>
                <td>
                  {% if is_granted("ROLE_ROOT") %}
                  <a href="{{ path('aulas_edit', {'id': aula.id}) }}"><i class="bi bi-pencil-square"></i></a>
                  {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">sin registros</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <a href="{{ path('edificios_index') }}" class="btn btn-sm btn-outline-secondary" role="button">volver</a>
{% endblock %}

templates/aulas/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nueva Aula{% endblock %}
{% block cardheader %}
	<div class="col-sm-11">
		<h5>Nueva Aula</h5>
	</div>
	<div class="col-sm-1">
         
	</div>
{% endblock %}
{% block cardbody %}
    {{ include('aulas/_form.html.twig') }}
    <a href="{{ path('aulas_index') }}" class="btn btn-sm btn-outline-secondary" role="button">volver</a>
{% endblock %}

templates/aulas/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Aulas
{% endblock %}
{% block cardheader %}
	<div class="col-sm-8">
		<h5>Aula</h5>
	</div>
	<div class="col-sm-2">
		<a href="{{ path('aulas_edit', {'id': aula.id}) }}" class="btn btn-outline-primary" role="button">Editar</a>
	</div>
	<div class="col-sm-2">
		{{ include('aulas/_delete_form.html.twig') }}
	</div>
{% endblock %}
{% block cardbody %}
	<table class="table table-sm table-striped table-borderless">
		<tbody>
			<tr>
				<th>Id</th>
				<td>{{ aula.id }}</td>
			</tr>
			<tr>
				<th>Aula</th>
				<td>{{ aula.aula }}</td>
			</tr>
			<tr>
				<th>Capacidad</th>
				<td>{{ aula.capacidad }}</td>
			</tr>
			<tr>
				<th>Edificio</th>
				<td>{{ aula.idEdificio.edificio }}</td>
			</tr>
		</tbody>
	</table>
	<a href="{{ path('aulas_index') }}" class="btn btn-sm btn-outline-secondary" role="button">volver</a>
{% endblock %}